### ISSUE TITLE
Error: Tried to construct an object without a GType

### ISSUE THREAD

**Issue by dbear496** [paradoxxxzero/gnome-shell-system-monitor-applet#713] opened 2021-09-11 17:15 UTC
I recently updated system-monitor-next via Firefox, and now the extension won't start. When I look in the Extensions app, it says `Error: Tried to construct an object without a GType`. I tried reinstalling the extension and rebooting, but it still does not start.

Info:
system-monitor-next: 36
GNOME: 40.2.0
OS: Ubuntu 21.10

**Comment by philb61** [comment] 2021-10-04 00:59
This seems to be a weird Wayland thing.  I was getting the same thing.  Logged in using Gnome instead, installed it, then switched back to Wayland, and all seems fine.  Very odd.

**Comment by chrisspen** [comment] 2021-11-26 22:44
This is a duplicate of issue #707.

**Closed by chrisspen** 2021-11-26 22:44 UTC

**Comment by mynam3isg00d** [comment] 2021-11-26 23:02
> I got the same error and I solved it by installing the extension with:
> 
> `sudo apt install gnome-shell-extension-system-monitor`
> 
> Then I restarted the gnome-shell.
> 
> Hope this can help you.

Very cool thanks

**Comment by dbear496** [comment] 2021-11-27 02:06
> I got the same error and I solved it by installing the extension with:
> 
> `sudo apt install gnome-shell-extension-system-monitor`
> 
> Then I restarted the gnome-shell.
> 
> Hope this can help you.

This worked for me. Odd I thought I had already tried this before. But now it works so I'm happy :slightly_smiling_face: .

**Comment by ruffson** [comment] 2022-01-10 22:10
> I got the same error and I solved it by installing the extension with:
> 
> `sudo apt install gnome-shell-extension-system-monitor`
> 
> Then I restarted the gnome-shell.
> 
> Hope this can help you.


For what it's worth, this also helped on Fedora 35 where this is also a problem (on either X11 or Wayland).
Package name is slightly different though:

```
sudo dnf install gnome-shell-extension-system-monitor-applet
```

**Comment by sideeffffect** [comment] 2022-07-04 01:43
According to https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/707#issuecomment-1022043919 installing `libgtop2-dev` solves this issue.

**Comment by mbana** [comment] 2022-08-26 10:43
> According to [#707 (comment)](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/707#issuecomment-1022043919) installing `libgtop2-dev` solves this issue. (You may need to restart, but the system-monitor will work eventually.)

Same here.

On Ubuntu 22.04.1 under Wayland installing `libgtop2-dev` did the trick:

```sh
sudo apt-get install gir1.2-gtop-2.0 gir1.2-nm-1.0 gir1.2-clutter-1.0 gnome-system-monitor gir1.2-gtop-2.0 gir1.2-nm-1.0 gir1.2-clutter-1.0 gnome-system-monitor gir1.2-gtop-2.0 gir1.2-nm-1.0 gnome-system-monitor libgtop2-dev
```

**Comment by progfou** [comment] 2022-11-15 01:32
Hi there!

On Ubuntu 22.10, installing the _runtime_ library package (not the development one) was enough to solve this problem for me:

> sudo apt install gir1.2-gtop-2.0

After doing this, you need to restart GNOME Shell to reload the extensions, either by using `Alt`+`F2` `r` `Enter` or by restarting the session.

Note that I'm running Xorg at the moment and also had this same problem, so it's probably not related to Wayland but to missing dependencies instead. BTW, the required dependencies are actually specified in the README file!

Last but not least, it appears there is a test for missing dependencies in the `extension.js` file, but it wasn't displayed. All I got was this `Tried to construct an object without a GType` error message in the extension manager.
