### ISSUE TITLE
requires alread installed lm-sensors 

### ISSUE THREAD

**Issue by ousia** [paradoxxxzero/gnome-shell-system-monitor-applet#236] opened 2014-01-25 17:59 UTC
I’m using commit 9ce5c5bacd packaged for Fedora 20 and I experience a weird issue.

In preferences, the fan tab has a drop-down menu for sensors, but when I click on it, I get a message: “Please install lm-sensors”.

Well, the weird thing is that (all available packages for) lm-sensors are installed on my Fedora distribution.

What am I missing here?

Many thanks for the excellent work.

**Comment by Zemogiter** [comment] 2018-03-22 00:24
I have the same issue. Already installed lm-sensors and sudo sensors-detect. The sensor command only shows temperatures. My motherboard is Gigabyte Z270 Gaming K3. Please help

**Comment by return42** [comment] 2019-09-28 12:41
@Zemogiter Does the problem still exist?

**Comment by tengwar** [comment] 2019-10-03 20:05
@return42 I can't check because lm-sensors started detecting my fan sensors. 😁

**Comment by return42** [comment] 2019-10-04 06:53
@tengwar  if now one can observe this error anymore, I would say it is fixed.

@ousia .. if so, can you please close the issue / thanks

**Comment by tengwar** [comment] 2019-10-06 11:11
@return42 More like "cannot reproduce" than "fixed" but yeah, I guess it can be closed until @Zemogiter answers.

**Closed** 2019-10-07 12:34 UTC

**Comment by eugenio** [comment] 2020-10-14 13:45
Is this issue fixed? I'm experiencing the same problem described here. I'm on ubuntu 18.04 and the machine is a tuxedo laptop.

**Comment by entodoays** [comment] 2021-05-03 20:50
I'm still getting the "please install lm-sensors" error. It doesn't happen all the time. It's like a lottery: one day it works, the next it doesn't. lm-sensors is installed and shows fan speed.

**Comment by hsh9544** [comment] 2021-07-12 21:55
I've the same problem. It was working fine, but after running `sensors-detect` it's asking to install `lm-sensors` for fan.

**Comment by krustophenia** [comment] 2021-12-20 11:37
> I've the same problem. It was working fine, but after running `sensors-detect` it's asking to install `lm-sensors` for fan.

+1 on Fedora 35 + gnome
