### ISSUE TITLE
GNOME 3.24 "Extension loading error"

### ISSUE THREAD

**Issue by develop7** [paradoxxxzero/gnome-shell-system-monitor-applet#345] opened 2017-03-24 14:18 UTC
Probably related lines in journal:

```
Extension "system-monitor@paradoxxx.zero.gmail.com" had error: TypeError: Main.__sm is undefined
Extension "system-monitor@paradoxxx.zero.gmail.com" had error: ReferenceError: GTop is not defined
```

**Comment by chrisspen** [comment] 2017-03-24 15:33
Thanks for the report. However, it looks like this is a duplicate of issue #341, for which there's a pending patch.

**Closed by chrisspen** 2017-03-24 15:33 UTC

**Comment by martindorey** [comment] 2019-11-20 19:38
If my interpretation of my experience is correct, "TypeError: Main.__sm.tray is undefined" might just mean that you need to Alt-F2 and r to restart gnome-shell for the newly installed dependencies to take effect.

**Comment by leorochael** [comment] 2020-08-17 20:08
I got to this page because I got the error message on the first line only.

Restarting gnome-shell as @martindorey reported is the right fix.

And yes, I had just installed `gir1.2-gtkclutter-1.0` because of another error message displayed in the extension config window.
