### ISSUE TITLE
Regular "micro-freezes" when extension is enabled in gnome-shell 3.6.3

### ISSUE THREAD

**Issue by adlorenz** [paradoxxxzero/gnome-shell-system-monitor-applet#202] opened 2013-02-18 11:57 UTC
Just upgraded Fedora to release 18 which comes with gnome-shell 3.6.3 and noticed annoying issue when system-monitor extension is enabled. The desktop suffers from "micro-freezes" which take just split-second yet are utterly annoying (ie. mouse or typing cursor chokes, often leaving unwanted effect). 

I've managed to nail the problem down to system-monitor, as these freezes stop happening when extension is disabled. Also, the freezes seem to occur in regular intervals, approx. every 4-5 seconds. I've tried to adjust extension settings and remove lesser used sensors, leaving just CPU and MEM sensors active, yet the problem didn't stop occurring.

**Comment by rzippert** [comment] 2015-01-01 16:09
I am experiencing this screen freeze issue but it's not related to any network or disk mounts. In my case it's related to reading the fan speeds with i8k and its been happening since I was using Fedora 19 (I'm now on 21). The freezes occur exactly in the time I set the fan readings to update. I've already removed i8k, however its option doesn't disappear from the fan drop down menu and, also, didn't stop the freezes. I'm using a Dell Vostro 2450 laptop with Fedora 21, so I'm not sure if i8k was supposed to work with it, but still, this is what causes the problem here. I'm now looking for some way to disable these fan readings definitely...

**Comment by aspexi** [comment] 2015-03-13 12:30
Hi guys

I had this issue for a long time and I couldn't figure out what causes this.

Happily I have found this topic. 

Currently I have:

Ubuntu 14.10
Gnome Shell 3.14.3
the latest gnome-shell-system-monitor-applet according to extensions.gnome.org

The issue occures.

Anyway, I've just downloaded the latest master codebase and compared it to my latest codebase. These files are different! (I have not modified them)

I've replaced all files with master and now the issue is gone.

The question is why extensions.gnome.org shows that I have the latest version of the plugin when I have not!?

**Comment by rzippert** [comment] 2015-03-14 02:27
As an update from the last message (1 january), tested again and no more freezes. No idea what has changed...

**Comment by laurentbriet** [comment] 2017-10-22 23:01
I'm experiencing micro freeze on a frequency around a second or two after updating to ubuntu 17.10 from 17.04. Disabling the extension and the freezes are gone.

**Comment by xiaosong0911** [comment] 2017-11-26 14:42
Micro freezes happen in every several minutes, with archlinux and gnome 3.26.2 in my laptop. Disabling this extension there is no problem.

**Comment by EvgeniiFrolov** [comment] 2018-01-23 08:49
Also experience micro-freezes on Fedora 27 with the extension installed via gnome-software.
Easy to reproduce in Evolution by opening a menu in the top or right-clicking in a message window for pop-up menu.

**Comment by RouHim** [comment] 2018-03-06 14:44
Same here on Ubuntu 17.10. Took me a while to figure it out that this extensions was it.

**Comment by tim-janik** [comment] 2018-04-05 11:00
Same here on Ubuntu 17.10. Enabling the extension (from todays git master) causes annoying interuptions with lag X11 screen rendering around every 1-1.5 seconds. Noticeable when scrolling in firefox, or when pressing 'w' in gnome-terminal with repeat, etc.

My current workaround is to use: https://extensions.gnome.org/extension/1043/gnomestatspro/
It's displaying CPU use without micro-freezing gnome-shell.

**Comment by daptordarattler** [comment] 2018-04-24 12:47
So I have had this issue on and off in my last few ubuntu installations for 4 years now. I never figured what the problems was until, i saw this thread now. 

So I dig some digging. I have had the gnome-system-monitor extension since Ubuntu 17.04, and update to 17.10 and i didnt have the problem until a few days ago. So afer following this thread, i realise that although the gnome-system-monitor is what reacts to the freezing its not the main culprit. Apparently I had some network/online file system shared in my gvfs and i had no idea where it came from. Also saw it in nautilus. 

After messing around and disabling it(halfly) the micro freezes stopped. Disabling gnome-system-monitor will also stop it, but the underlying issue will be there. And since i really like that extension i decided to share my experience to help others find those hidden gvfs mounts that are actually causing the problem.

Also: My gvfs mount was related to my inline google account. I still cant figure out how it got there.

Hope this helps.

**Comment by JochemKuijpers** [comment] 2018-11-14 00:32
Same problem here (Ryzen R7 1700X), disabling CPU frequency in both the top bar and the drop-down menu entirely seems to fix it.

I wouldn't mind helping debug this, but I have no idea where to start. Whoever needs more information, mention me if you need me.

**Comment by Kagetsuki** [comment] 2018-11-24 08:55
Just in case somebody assumes this is a Ryzen issue from the above two posts I have an Intel i7 8700k and I have the same issue. Currently just have the extension completely disabled because of this.

**Comment by HetorusNL** [comment] 2018-12-25 15:42
I don't know whether this helps someone, but in my case enabling seconds in the top bar in the tweak tool caused 'micro-freezes':

Tweak tool => Top Bar => Clock => Seconds: Enabled

These freezes occur every second (literally) in multiple applications, including python (pygame).
When the second increments, a slight freeze happens.

**Comment by HetorusNL** [comment] 2018-12-25 18:56
I don't know whether this helps someone, but in my case enabling seconds in the top bar in the tweak tool caused 'micro-freezes':

Tweak tool => Top Bar => Clock => Seconds: Enabled

These freezes occur every second (literally) in multiple applications, including python (pygame).
When the second increments, a slight freeze happens.

**Comment by return42** [comment] 2019-02-24 12:52
@adlorenz 

>  leaving just CPU and MEM sensors active, yet the problem didn't stop occurring.

This issue is fixed in master since PR #497 is merged. Can you please test current master and close this issue? / Thanks!

**Closed** 2019-09-24 17:56 UTC

**Comment by Kagetsuki** [comment] 2019-09-25 02:42
Already closed but just let me confirm the issue seems to be resolved and the extension is now working fine for me.
