### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by BloodyIron** [paradoxxxzero/gnome-shell-system-monitor-applet#710] opened 2021-09-04 20:39 UTC
So is this extension abandoned?

**Comment by p91paul** [comment] 2021-09-04 23:20
Well last commit is less than 2 weeks old, so I'd say it's not abandoned.

**Comment by BloodyIron** [comment] 2021-09-06 04:11
Last release April 2019, doesn't even have GNOME 40 support, let alone 41.

So...? Abandoned-ish.

**Comment by p91paul** [comment] 2021-09-06 07:32
It's just not updated on extensions.gnome.org, there are already opened issues for that. On this repository the master branch fully supports Gnome 40. Follow manual installation instructions.

**Comment by BloodyIron** [comment] 2021-09-06 16:13
No, I'm talking about the release section of _this github project_ has a last release date of April 2019. Can we get a new release and update on the extensions page already please?

**Comment by p91paul** [comment] 2021-09-06 18:37
I think this issue can be closed as duplicate of  https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/706, https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/672 and others

**Comment by gfoligna** [comment] 2021-09-07 21:23
I guess this has been fixed by https://extensions.gnome.org/extension/3010/system-monitor-next/

**Comment by chrisspen** [comment] 2021-09-08 21:58
A new release is now live on extensions.gnome.org.

**Closed by chrisspen** 2021-09-08 21:58 UTC
