### ISSUE TITLE
extension.js tweak for  gnome-shell 3.24 

### ISSUE THREAD

**Issue by dino99** [paradoxxxzero/gnome-shell-system-monitor-applet#341] opened 2017-02-18 08:30 UTC
Ubuntu Zesty use gnome-shell 3.23.90 (3.24) version now
but that extension is not yet compatible;

GNOME Shell 3.24 now uses mozjs38 (SpiderMonkey 38) which has stricter syntax rules.
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey

 please do asap
Thanks

**Comment by p91paul** [comment] 2017-02-18 10:04
Given that extension version check is disabled by default since 3.20 or 3.22 AFAIR, you should be able to install and try this extension on latest gnome-shell following manual install instructions on this repository home page: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet

**Comment by PSSGCSim** [comment] 2017-02-21 14:36
Yes but even after I've changed manifest it doesn't work. Gnome Tweaks says "Error loading extension" so I'm guessing there might be a different problem than version check. I've checked with `lg` and it prints out this error:
![screenshot from 2017-02-21 15-35-35](https://cloud.githubusercontent.com/assets/7548851/23169292/845becca-f84b-11e6-92a8-8fa20c2f35a3.png)

**Comment by franglais125** [comment] 2017-02-21 22:50
@PSSGCSim That sounds more like you are missing a dependency:

`sudo apt install gir1.2-gtop-2.0 gir1.2-networkmanager-1.0`

**Comment by PSSGCSim** [comment] 2017-02-22 14:08
@franglais125 No, as I've got all these installed.
```
pssgcsim@ps1 : ~ [0]$ sudo apt install gir1.2-gtop-2.0 gir1.2-networkmanager-1.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-gtop-2.0 is already the newest version (2.34.2-1).
gir1.2-networkmanager-1.0 is already the newest version (1.4.4-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by franglais125** [comment] 2017-02-22 22:10
So, I installed Ubuntu Zesty (Gnome version) on a VM to see what was going on.
I really doubt this is a problem with the extension. Gnome-shell is spitting a **lot** of errors on its own. This is a beta version of the Shell, and perhaps some other package is still to be updated in Ubuntu, who knows.
I tried this on a clean install, the only thing I had to install was the gir bindings.
You can try to run `gnome-shell --replace` on a terminal, and see for yourself (see below).
Perhaps as Zesty updates some other packages or gnome-shell 3.24 becomes more stable, this problem will go away... As it is, impossible to debug.

```
gnome-shell --replace
GNOME Shell-Message: WARNING: addSignalMethods is replacing existing [object prototype of GType:Gjs_ShowOverviewAction jsobj@0x7f4ba0f22b80] connect method
GNOME Shell-Message: WARNING: addSignalMethods is replacing existing [object prototype of GType:Gjs_ShowOverviewAction jsobj@0x7f4ba0f22b80] disconnect method
GNOME Shell-Message: WARNING: addSignalMethods is replacing existing [object prototype of GType:Gjs_ShowOverviewAction jsobj@0x7f4ba0f22b80] emit method
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/main.js 317]: reference to undefined property global.stage
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 217]: reference to undefined property global.window_group
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 899]: reference to undefined property this.monitors[this.findIndexForActor(...)]
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property Meta.MonitorManager
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/panel.js 1107]: reference to undefined property indicator.menu._openChangedId
Gjs-Message: JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 538]: reference to undefined property properties[istr].arrayIndex
current session already has an ibus-daemon.
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 34]: reference to undefined property St.GenericAccessible
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/messageList.js 391]: reference to undefined property this._useBodyMarkup
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/search.js 432]: reference to undefined property provider.isRemoteProvider
system-monitor-Message: System monitor applet init from /home/franglais125/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com
system-monitor-Message: System monitor applet enabling
GNOME Shell-Message: Extension "system-monitor@paradoxxx.zero.gmail.com" had error: ReferenceError: GTop is not defined
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/messageList.js 169]: reference to undefined property this._container
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/misc/ibusManager.js 196]: reference to undefined property this._engines[id]
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/status/network.js 1885]: reference to undefined property this._mainConnectionStateChangedId
```

**Comment by simonsonc** [comment] 2017-03-15 03:23
I think the problem is that newer versions of either SpiderMonkey or gnome-shell don't like the whole defining a variable in the "try" section. Saying:

```
var GTop;                                                                        
try {                                                                            
    GTop = imports.gi.GTop; 
```

and doing the same for NMClient and NetworkManager fixed it for me. I'm not sure what the correct fix should be.

**Comment by dino99** [comment] 2017-03-16 11:17
Thanks for the findings

This is the changes made starting at line ~ 42 of  extension.js
*******
var GTop; //added
try {
//    const GTop = imports.gi.GTop;
     GTop = imports.gi.GTop; // added
} catch(e) {
    log(e);
    smDepsGtop = false;
}

try {
//    const NMClient = imports.gi.NMClient;
//    const NetworkManager = imports.gi.NetworkManager;
    NMClient = imports.gi.NMClient; //added
    NetworkManager = imports.gi.NetworkManager; //added
} catch(e) {
    log(e);
    smDepsNM = false;
}
*******
then alt+F2+r to restart gnome-shell, and the extension icons are back in the systray, and working fine.

**Comment by dino99** [comment] 2017-03-16 14:24
had closed by error while i made the previous comment; let it open as users may need to know about the tweaks until a new version

**Comment by franglais125** [comment] 2017-03-19 21:25
I prepared a patch for this. [2b6cc9e91f8075ff35f3297ba9b4110b0736a036]

**Comment by nschloe** [comment] 2017-03-24 11:21
In which branch will I find this commit? Has it landed in master yet?

**Comment by franglais125** [comment] 2017-03-24 11:24
It's the master branch here: https://github.com/franglais125/gnome-shell-system-monitor-applet

You can:
```
git clone https://github.com/franglais125/gnome-shell-system-monitor-applet
cd gnome-shell-system-monitor-applet
make && make install
```

Or install from zip file.

**Comment by marxin** [comment] 2017-03-25 16:19
@franglais125 Are you planning to create a pull request to this git repository?

**Comment by franglais125** [comment] 2017-03-27 18:55
Ah, sorry, I was actually waiting for @chrisspen to pull it, as it's really a simple fix. But I see that someone else already opened a pull!

**Closed** 2017-03-27 20:22 UTC

**Comment by marxin** [comment] 2017-03-27 20:58
Thanks @chrisspen. Are you planning to submit the version to extensions.gnome.org?

**Comment by chrisspen** [comment] 2017-03-28 18:32
@marxin, Not immediately. Probably in the next week or so.

**Comment by JamesChristie** [comment] 2017-04-14 18:15
@chrisspen Any news on updates to the gnome extensions site? I'd love to move off of a manual install. The version on the gnome site is broke due to this fixed issue on Ubuntu 17.04.

**Comment by chrisspen** [comment] 2017-04-21 22:06
@JamesChristie I'm still seeing some reports of the extension not working for some on 17.04. As soon as these get resolved and stay resolved for a week or so, then I'll push a release to extensions.gnome.org.

**Comment by JamesChristie** [comment] 2017-04-21 22:17
@chrisspen I just cloned the repo and installed it from a detached HEAD on the latest tag and it worked perfectly. The version that's broken on 17.04 is the older version uploaded to the extensions website was the understanding I had come to.

**Comment by franglais125** [comment] 2017-04-21 22:21
@chrisspen Just to give some positive feedback: once you merged #347, it seems to me that the reports of problems have been due to missing dependencies, not problems with the extensions itself.

**Comment by JamesChristie** [comment] 2017-04-21 22:27
I did indeed have to install some gir packages (two, I believe), but I got a nice popup telling me exactly what to install for it to work. Unless you meant different dependencies.

**Comment by franglais125** [comment] 2017-04-21 22:30
@JamesChristie Precisely. Those dependencies have to be installed manually. But of course that's not a problem with the extension :)

**Comment by JamesChristie** [comment] 2017-05-03 02:03
For anyone wondering, it appears as though this issue is now happily resolved. Also Gnome extensions alert of updates even when installed manually. I did not know that before, but it is awesome. Thanks @chrisspen for the awesome extension. :+1:

**Comment by chrisspen** [comment] 2017-05-03 03:02
@JamesChristie Thanks, although I'm more of a caretaker. @franglais125 and others have done most of the actual development.

**Comment by return42** [comment] 2019-09-28 13:03
@dino99 do you still have problems? If not, lets close this issue / thanks
