### ISSUE TITLE
Gnome 40 Settings issue

### ISSUE THREAD

**Issue by l3ycle** [paradoxxxzero/gnome-shell-system-monitor-applet#690] opened 2021-04-30 10:49 UTC
Hi
I'm on ArchLinux Gnome 40 and when I want to change the settings of this extension via the "Extensions" window. But this error shows up:
```
The settings of extension system-monitor@paradoxxx.zero.gmail.com had an error:

Error: No property border_width on GtkFrame

Stack trace:

_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
SystemMonitor@/usr/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:198:22
SystemMonitor_App/<@/usr/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:352:38
SystemMonitor_App@/usr/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:351:23
buildPrefsWidget@/usr/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:424:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Is there any solution for this issue?

**Comment by adrienverge** [comment] 2021-04-30 13:42
Hello @l3ycle, I can confirm the same error on Fedora 34 with GNOME Shell 40.0, but I think your issue is a duplicate of https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/659.

**Comment by p91paul** [comment] 2021-04-30 22:19
this is fixed in https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/678

**Comment by Digitalone1** [comment] 2021-05-03 18:09
If this is fixed, why don't you merge the PR?

**Closed** 2021-05-04 06:06 UTC
