### ISSUE TITLE
Issues with gvfs interaction

### ISSUE THREAD

**Issue by camelreef** [paradoxxxzero/gnome-shell-system-monitor-applet#207] opened 2013-04-19 04:50 UTC
Hello,

Ubuntu 12.10 and 13.04 with the Gnome 3 PPA, Gnome 3.6 and 3.8
- the system does not go fully into suspend and comes back to the shell, sometimes into a broken state if there is a gvfs mount
- shell fully frozen while doing a file transfer using the MTP gvfs backend
- shell freeze if mounted iPhone is removed
- regular shell/UI freezes

All of this disappears if the extension is disabled

It's a shame, I love the extension otherwise!

**Comment by cryptoluks** [comment] 2015-02-20 21:16
I can confirm this issue.
Arch Linux x86_64 3.18.7-2-ck
GNOME Shell 3.14.3

**Comment by daptordarattler** [comment] 2018-04-24 12:52
I can confirm this issue with Ubuntu 17.10 and latest gnome-shell and gnome-system-monitor. Helped my find a hidden gvfs I didn’t kno about.

**Comment by chrisspen** [comment] 2019-09-24 18:01
Can anyone confirm this problem exists on Ubuntu 18.04 or later? I'm experiencing no issues.

**Comment by jjcf89** [comment] 2019-09-24 18:37
Running 18.04 and my gnome-shell freezes up fairly regularly.  Though I can't guarantee its still this issue like it was in the past.

**Comment by chrisspen** [comment] 2019-09-24 18:44
And the problem goes away if you disable this extension?

**Comment by jjcf89** [comment] 2019-09-24 20:17
I don't have an easily reproducible way to trigger this to test for sure.

**Comment by return42** [comment] 2019-09-27 10:11
@chrisspen, @jjcf89 .. can we close this thread and continue discussion in #226  (started 2015)

@camelreef if it is OK for you, can you please close this issue (started 2013)?

**Comment by return42** [comment] 2019-09-27 10:14
@chrisspen @jjcf89 @camelreef  .. forget my last post .. I was a bit confused .. sorry for the noise.

**Comment by return42** [comment] 2019-09-28 12:38
I can confirm, that the extension works with ubu18-04. / lets close this old issue.

**Closed** 2019-09-29 03:25 UTC

**Comment by jjcf89** [comment] 2019-09-30 00:09
> I can confirm, that the extension works with ubu18-04. / lets close this old issue.

The fact that the extension works in 18.04 is hardly proof that this bug has been fixed as I don't think the bug resolves around whether the plugin works or not.  But whether it hangs the system based on gvfs interactions.

Issue #496 does seem to resemble the issue.

**Comment by return42** [comment] 2019-09-30 08:40
We have a lot issues entries are related to synchronous IO problem. In #496 I try to assemble those entries.  This bug report is from 2013, many issues have been solved since. @chrisspen (https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/207#issuecomment-534677243)  and I do not have problems. You answered him that you can't reproduce the problem.

So please let us close this old entry from 2013. If you detect further issues with a more up-to-date release, please insert a new entry with a up-to-date error description.





 setup and   if you detect further problems

**Comment by jjcf89** [comment] 2019-09-30 13:37
Sorry, I think collecting them in #496 is reasonable.  My hope with my post was to direct people who stumble on this issue there.
