### ISSUE TITLE
ubuntu 18.10, gnome 3.30.1 nvidia quadro p600. . . v37 update

### ISSUE THREAD

**Issue by ndp-stc** [paradoxxxzero/gnome-shell-system-monitor-applet#514] opened 2019-03-21 04:48 UTC
very recent update installed through gnome shell extension: suddenly, Gnome shell has become stable for the first time.

Prior to this, there were very frequent hangs, crashes and core-dumps. I was unable to pin it down to this particular extension, but by disabling all extensions I was unable to reproduce the instability. 

When I re-enabled my extensions, one-by-one, my system resumed random issues: various symptoms including: freeze-on-wake-from-suspend. Failure to screen-lock. Randomly-spaced gnome resets. Random gnome crashes (requiring login, and restart of all applications). Login fail loops (requiring login via alternate terminal and delete of .Xauthority file).

Whatever changed between the previous version, and version 37, seems to have made my system much more stable, and this was the only update I installed today. 

Other extensions loaded:
clipboard-indicator
coverflow-alt-tab
gno-menu
open weather
sound input & output device chooser (also recently updated)
system-monitor
unite

**Comment by chrisspen** [comment] 2019-03-21 13:08
I'm glad the new release is working better for you. However, this sounds like feedback, and not a bug report, so I'm going to close it. Please correct me if I'm wrong.

**Closed by chrisspen** 2019-03-21 13:08 UTC

**Comment by ndp-stc** [comment] 2019-03-22 16:19
correct - this is just feedback, thank you!

I would have filed a bug report when the problem was occurring, but there were too many random symptoms and too much noise in the logs for me to figure out exactly what the problem was.
